config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/admin/chat/history', to: 'admin/chat#history'

  # namespace :admin do
  #   get 'dashboard', to: 'admin_dashboard#index'
  # end

  # Resister User controller routes
  post 'register', to: 'users#create'
  post '/verify_otp', to: 'users#verify_otp'
  post 'login', to: 'users#login'

  # Customer
  resources :customers, only: [:index, :create, :destroy]
  post 'customer_payment_detail', to: 'customers#customer_payment_detail'
  
  # Customer Tiffin
  resources :customers do
    resources :tiffins, only: [:index, :create, :update, :destroy]
  end

  # Stripe
  namespace :payment do
    post 'stripe/charge', to: 'stripe#charge'
  end

  # OTP
  post 'send_otp', to: 'users#send_otp'
  devise_for :users
  post 'generate_otp', to: 'users#generate_otp'
  post 'verify_otp', to: 'users#verify_otp'

  # chat_message
  resources :chat_messages, only: [:index, :create]

  resources :chat_messages do
    collection do
      get :history
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :customers
  has_many :chat_messages
  has_secure_password

  validates :user_name, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  before_create :generate_otp

  def generate_otp
    self.otp = rand(1000..9999).to_s
    self.otp_generated_at = Time.current
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "name", "number", "otp", "otp_generated_at", "otp_verified", "password_digest", "stripe_customer_id", "updated_at", "user_name"]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: %i[login create verify_otp]

  def create
    @user = User.new(user_params.except(:otp, :otp_generated_at, :otp_verified))
    if @user.save
      UserMailer.with(user: @user, otp: @user.otp).otp_email.deliver_later
      render json: { message: 'OTP sent to your email. Please verify.' }, status: :created
    else
      render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity 
    end
  end

  def login
    user = User.find_by(user_name: params[:user_name])
    if user&.authenticate(params[:password])
      if user.otp_verified
        payload = { user_id: user.id }
        token = encode(payload)
        render json: { message: 'Login successful!', token:, user_name: user.user_name, name: user.name },
               status: :ok
      else
        render json: { error: 'OTP not verified. Please verify your OTP first.' }, status: :unauthorized
      end
    else
      render json: { error: 'Invalid username or password' }, status: :unauthorized
    end
  end

  def verify_otp
    user = User.find_by(user_name: params[:user_name])

    if user && user.otp == params[:otp] && user.otp_generated_at > 20.minutes.ago
      user.update_column(:otp_verified, true)
      render json: { message: 'OTP verified, registration complete.' }, status: :ok
    else
      render json: { message: 'Invalid or expired OTP' }, status: :unauthorized
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_name, :email, :number, :password, :otp, :otp_generated_at, :otp_verified)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_name, style: "display: block" %>
    <%= form.text_field :user_name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>User name:</strong>
    <%= user.user_name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Welcome!</h1>
<p>Please choose an option:</p>

<div>
  <%= link_to 'Login', login_path, class: 'btn btn-primary' %>
  <%= link_to 'Register', register_path, class: 'btn btn-secondary' %>
</div>

app/views/users/login.html.erb
<h1>Login</h1>
<% if flash[:notice] %>
  <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>

<%= form_with url: login_path, method: :post, local: true do |form| %>
  <div>
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit 'Login', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back to Home', root_path %>

app/views/users/login_success.html.erb
<h1>Login Success!</h1>
<p><%= session[:user_name] %> has successfully logged in.</p>

<%= link_to 'Create Customer', new_customer_path, class: 'btn btn-primary' %>

<!-- Search Section -->
<%= form_with url: login_success_path, method: :get, local: true do |form| %>
  <div>
    <%= form.label :search, 'Search Customer by Name' %>
    <%= form.text_field :search, value: params[:search], placeholder: "Enter customer name" %>
    <%= form.submit 'Search', class: 'btn btn-secondary' %>
  </div>
<% end %>

<h2>Customer List</h2>

<% if @customers.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Mobile No</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.name %></td>
          <td><%= customer.mobile_no %></td>
          <td><%= customer.address %></td>
          <td>            
           <%= link_to 'Tiffin Entry', customer_tiffins_path(customer), class: 'btn btn-info' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No customers found.</p>
<% end %>

<%= link_to 'Back to Home', root_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with model: @user, url: register_path, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit 'Register', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>